### ISSUE TITLE
This site should have an 'about' page with information about the eReefs collaboration

### ISSUE THREAD

**Issue by sharon-tickell** [eReefs/ereefs.github.io#1]
Content from the old ereefs.org.au site (may need updating, but let's start with that)

https://ereefs.org.au/ereefs/about

**Comment by david-sh-csiro** [comment]
The attached link appears invalid as it was most likely from the old system. From looking through both the live version of the app and the local development environment, this ticket appears complete as there is an about section that has information on the collaborators AIMS, BOM and CSIRO.
