### ISSUE TITLE
This site should list and link to all eReefs funders

### ISSUE THREAD

**Issue by sharon-tickell** [eReefs/ereefs.github.io#3]
Including GBRF (https://www.barrierreef.org/what-we-do/projects/eReefs) and SIEF (https://sief.org.au/csiro-gift/what-has-been-funded/what-has-been-funded-research-projects-program/ereefs-research-project/)

**Comment by sharon-tickell** [comment]
GBRF probably belongs in the funders list, rather than the collaborators list

**Comment by david-sh-csiro** [comment]
This looks to be complete. I can see both SIEF and GBRF listed as funders on the live and development versions of the site.
