### ISSUE TITLE
Use the new CSIRO-developed eReefs Visual Identity

### ISSUE THREAD

**Issue by sharon-tickell** [eReefs/ereefs.github.io#4]
Documented inside CSIRO at https://confluence.csiro.au/display/ER/Visual+Identity

**Comment by david-sh-csiro** [comment]
Looking at the source CSS files for the live and dev versions of the websites, it is clear some of the linked stylesheets have been used. (e.g. ereefs-overrides.css and ereefs-reset.css) The attached logo is also prominently featured on the page and as the favicon. In terms of attached fonts, Roboto and OpenSansCondensed are loaded as styles for both the live and dev site. From a cursory look through the attached document the website looks to conform with the visual identity.
